Fjerner duplikate config-filer. Setter opp deploy til prod-gcp

diff --git a/.github/workflows/deploy.prod-gcp.yml b/.github/workflows/deploy.prod-gcp.yml
--- a/.github/workflows/deploy.prod-gcp.yml
+++ b/.github/workflows/deploy.prod-gcp.yml
@@ -1,12 +1,16 @@
-name: Deploy-to-q6
+name: Deploy-to-prod
 on:
-  workflow_dispatch
+  release:
+    types: [released]
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
+      - name: Abort if branch is not master
+        if: github.event.release.target_commitish != 'master'
+        run: echo "Release is not on master, aborting"; exit 1;
       - name: Define build environment
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -20,10 +24,10 @@ jobs:
         run: |
           cat > .env <<EOF
           NODE_ENV=production
-          APP_ORIGIN=https://www-q6.nav.no
+          APP_ORIGIN=https://www.nav.no
           APP_BASE_PATH=/sok
-          DECORATOR_URL=https://www-q6.nav.no/dekoratoren
-          XP_ORIGIN=https://www-q6.nav.no
+          DECORATOR_URL=https://www.nav.no/dekoratoren
+          XP_ORIGIN=https://www.nav.no
           EOF
       - uses: actions/cache@v2
         with:
@@ -41,15 +45,15 @@ jobs:
       - name: Generate nais variables
         run: |
           cat > .nais/vars.yaml <<EOF
-          namespace: q6
+          namespace: personbruker
           ingresses:
-            - https://www-q6.nav.no/sok
+            - https://www.nav.no/sok
           image: $IMAGE_REGISTRY/$IMAGE_NAME
           version: $IMAGE_VERSION
           EOF
       - uses: nais/deploy/actions/deploy@master
         env:
-          CLUSTER: dev-sbs
+          CLUSTER: prod-gcp
           APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
           RESOURCE: .nais/config.yaml
           VARS: .nais/vars.yaml
